[package]
name = "github-rustlang-webhook-server"
version = "0.1.0"
authors = ["Mark S. Everitt <mark.s.everitt@gmail.com>"]

[dependencies]
github_webhook_message_validator = "0.1.1"
rustc-serialize = "0.3.19"
